### ISSUE TITLE
jburzynski.net Internal Server Error

### ISSUE THREAD

**Issue by brandonryan** [jburzynski/TypeGenDocs#8]
Having trouble accessing the documentation. Getting a 500.
http://jburzynski.net/TypeGen/api-reference/api/TypeGen.Core.GeneratorOptions.html

**Comment by jburzynski** [comment]
API reference was moved from jburzynski.net to [FuGet](https://www.fuget.org/packages/TypeGen). But recently FuGet hasn't been working very well (throws exceptions frequently), so in the future maybe I'll find another way to host it.

**Comment by brandonryan** [comment]
Yeah I can never get FuGet to load...

**Comment by brandonryan** [comment]
Maybe look into using [ApiMundo](https://apimundo.com/)? The creator of NSwag and NJsonSchema made it. Seems to work well.

**Comment by jburzynski** [comment]
Maybe I'll check it out, thanks for suggesting.
